# Generated by Django 5.0.6 on 2026-06-11 23:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('pieza_id', models.AutoField(db_column='PiezaId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=300, null=True)),
                ('material', models.CharField(db_column='Material', max_length=100)),
                ('es_original', models.BooleanField(db_column='EsOriginal', default=False)),
                ('fecha_mod', models.DateTimeField(auto_now=True, db_column='FechaMod')),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'db_table': 'Pieza',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(db_column='ProductoId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=300, null=True)),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha_mod', models.DateTimeField(auto_now=True, db_column='FechaMod')),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='AsignacionPieza',
            fields=[
                ('asignacion_pieza_id', models.AutoField(db_column='AsignacionPiezaId', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad', validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_mod', models.DateTimeField(auto_now=True, db_column='FechaMod')),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('pieza', models.ForeignKey(db_column='PiezaId', on_delete=django.db.models.deletion.RESTRICT, to='inventario.pieza')),
                ('producto', models.ForeignKey(db_column='ProductoId', on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'db_table': 'AsignacionPieza',
            },
        ),
    ]
